// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ribbons.Users.Data;

#nullable disable

namespace Ribbons.Users.Migrations.Sqlite
{
    [DbContext(typeof(UserDbSqlite))]
    [Migration("20241113072202_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Ribbons.Users.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_date");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<long>("UserStatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_status_id");

                    b.Property<long>("UserTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_type_id");

                    b.HasKey("UserId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("ModifiedDate");

                    b.HasIndex("UserName");

                    b.HasIndex("UserStatusId");

                    b.HasIndex("UserTypeId");

                    b.HasIndex("UserTypeId", "UserName")
                        .IsUnique();

                    b.ToTable("t_user");
                });

            modelBuilder.Entity("Ribbons.Users.UserEmail", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("email_address");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_verified");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_date");

                    b.Property<long>("UserTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_type_id");

                    b.Property<DateTime?>("VerifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("verified_date");

                    b.HasKey("UserId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("EmailAddress");

                    b.HasIndex("IsVerified");

                    b.HasIndex("ModifiedDate");

                    b.HasIndex("UserTypeId");

                    b.HasIndex("VerifiedDate");

                    b.HasIndex("UserTypeId", "EmailAddress")
                        .IsUnique();

                    b.ToTable("t_user_email");
                });

            modelBuilder.Entity("Ribbons.Users.UserGroup", b =>
                {
                    b.Property<long>("UserGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_group_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("UserTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_type_id");

                    b.HasKey("UserGroupId");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("ModifiedDate");

                    b.HasIndex("UserTypeId");

                    b.HasIndex("UserTypeId", "Code")
                        .IsUnique();

                    b.ToTable("t_user_group");
                });

            modelBuilder.Entity("Ribbons.Users.UserGroupUser", b =>
                {
                    b.Property<long>("UserGroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_group_id");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("UserGroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("t_user_group_user");
                });

            modelBuilder.Entity("Ribbons.Users.UserPassword", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_expired");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_date");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("BLOB")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("BLOB")
                        .HasColumnName("password_salt");

                    b.HasKey("UserId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("IsExpired");

                    b.HasIndex("ModifiedDate");

                    b.ToTable("t_user_password");
                });

            modelBuilder.Entity("Ribbons.Users.UserPhone", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_verified");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_date");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone_number");

                    b.Property<long>("UserTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_type_id");

                    b.Property<DateTime?>("VerifiedDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("verified_date");

                    b.HasKey("UserId");

                    b.ToTable("t_user_phone");
                });

            modelBuilder.Entity("Ribbons.Users.UserSession", b =>
                {
                    b.Property<byte[]>("UserSessionId")
                        .HasMaxLength(64)
                        .HasColumnType("BLOB")
                        .HasColumnName("user_session_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_expired");

                    b.Property<byte[]>("SessionSecretHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("BLOB")
                        .HasColumnName("session_secret_hash");

                    b.Property<byte[]>("SessionSecretSalt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("BLOB")
                        .HasColumnName("session_secret_salt");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("UserSessionId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("IsExpired");

                    b.HasIndex("UserId");

                    b.ToTable("t_user_session");
                });

            modelBuilder.Entity("Ribbons.Users.UserStatus", b =>
                {
                    b.Property<long>("UserStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_status_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("UserTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_type_id");

                    b.HasKey("UserStatusId");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("ModifiedDate");

                    b.HasIndex("UserTypeId");

                    b.HasIndex("UserTypeId", "Code")
                        .IsUnique();

                    b.ToTable("t_user_status");
                });

            modelBuilder.Entity("Ribbons.Users.UserToken", b =>
                {
                    b.Property<byte[]>("UserTokenId")
                        .HasMaxLength(64)
                        .HasColumnType("BLOB")
                        .HasColumnName("user_token_id");

                    b.Property<DateTime?>("ConsumedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("consumed_date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_consumed");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_expired");

                    b.Property<byte[]>("TokenSecretHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("BLOB")
                        .HasColumnName("token_secret_hash");

                    b.Property<byte[]>("TokenSecretSalt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("BLOB")
                        .HasColumnName("token_secret_salt");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<long>("UserTokenTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_token_type_id");

                    b.HasKey("UserTokenId");

                    b.HasIndex("ConsumedDate");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("IsConsumed");

                    b.HasIndex("IsExpired");

                    b.HasIndex("UserId");

                    b.HasIndex("UserTokenTypeId");

                    b.ToTable("t_user_token");
                });

            modelBuilder.Entity("Ribbons.Users.UserTokenType", b =>
                {
                    b.Property<long>("UserTokenTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_token_type_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("UserTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_type_id");

                    b.HasKey("UserTokenTypeId");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("ModifiedDate");

                    b.HasIndex("UserTypeId");

                    b.HasIndex("UserTypeId", "Code")
                        .IsUnique();

                    b.ToTable("t_user_token_type");
                });

            modelBuilder.Entity("Ribbons.Users.UserType", b =>
                {
                    b.Property<long>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_type_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("UserTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("ModifiedDate");

                    b.ToTable("t_user_type");
                });

            modelBuilder.Entity("Ribbons.Users.User", b =>
                {
                    b.HasOne("Ribbons.Users.UserStatus", "UserStatus")
                        .WithMany("Users")
                        .HasForeignKey("UserStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ribbons.Users.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserStatus");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Ribbons.Users.UserEmail", b =>
                {
                    b.HasOne("Ribbons.Users.User", "User")
                        .WithOne("UserEmail")
                        .HasForeignKey("Ribbons.Users.UserEmail", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ribbons.Users.UserGroup", b =>
                {
                    b.HasOne("Ribbons.Users.UserType", "UserType")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Ribbons.Users.UserGroupUser", b =>
                {
                    b.HasOne("Ribbons.Users.UserGroup", "UserGroup")
                        .WithMany("UserGroupUsers")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ribbons.Users.User", "User")
                        .WithMany("UserGroupUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("Ribbons.Users.UserPassword", b =>
                {
                    b.HasOne("Ribbons.Users.User", "User")
                        .WithOne("UserPassword")
                        .HasForeignKey("Ribbons.Users.UserPassword", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ribbons.Users.UserPhone", b =>
                {
                    b.HasOne("Ribbons.Users.User", "User")
                        .WithOne("UserPhone")
                        .HasForeignKey("Ribbons.Users.UserPhone", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ribbons.Users.UserSession", b =>
                {
                    b.HasOne("Ribbons.Users.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ribbons.Users.UserStatus", b =>
                {
                    b.HasOne("Ribbons.Users.UserType", "UserType")
                        .WithMany("UserStatuses")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Ribbons.Users.UserToken", b =>
                {
                    b.HasOne("Ribbons.Users.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ribbons.Users.UserTokenType", "UserTokenType")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserTokenTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserTokenType");
                });

            modelBuilder.Entity("Ribbons.Users.UserTokenType", b =>
                {
                    b.HasOne("Ribbons.Users.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Ribbons.Users.User", b =>
                {
                    b.Navigation("UserEmail");

                    b.Navigation("UserGroupUsers");

                    b.Navigation("UserPassword");

                    b.Navigation("UserPhone");

                    b.Navigation("UserSessions");

                    b.Navigation("UserTokens");
                });

            modelBuilder.Entity("Ribbons.Users.UserGroup", b =>
                {
                    b.Navigation("UserGroupUsers");
                });

            modelBuilder.Entity("Ribbons.Users.UserStatus", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Ribbons.Users.UserTokenType", b =>
                {
                    b.Navigation("UserTokens");
                });

            modelBuilder.Entity("Ribbons.Users.UserType", b =>
                {
                    b.Navigation("UserGroups");

                    b.Navigation("UserStatuses");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
